#!/usr/bin/env php
<?php

use Schnittstabil\Sugared\PHPMD\TextUI\Application;

foreach ([
    __DIR__.'/../../autoload.php',
    __DIR__.'/../vendor/autoload.php',
    __DIR__.'/vendor/autoload.php',
    ] as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

unset($file);

if (!ini_get('date.timezone')) {
    date_default_timezone_set('UTC');
}

exit((new Application())->main($_SERVER['argv']));
